---
version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DB_PORT}:5432
    volumes:
      - type: volume
        source: pg-data
        target: ${DB_INSIDE_VOLUME}

volumes:
  pg-data:
